name: zic
base: core22
version: 0.1.0
summary: A command-line image conversion tool written in Zig
description: |
  zic converts images between BMP, PNG, and JPEG formats. It has zero
  third-party dependencies — all image codec implementations are included.

grade: stable
confinement: strict

apps:
  zic:
    command: bin/zic
    plugs:
      - home
      - removable-media

parts:
  zig:
    plugin: nil
    build-packages:
      - curl
      - xz-utils
    override-build: |
      snap install zig --classic --beta

  zic:
    after: [zig]
    plugin: nil
    source: .
    override-build: |
      export PATH="$SNAPCRAFT_STAGE/zig:$PATH"
      zig build -Doptimize=ReleaseFast
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp zig-out/bin/zic $SNAPCRAFT_PART_INSTALL/bin/
    stage-packages:
      - libc6
